### ISSUE TITLE
Error: ffmpeg.wasm is not ready, make sure you have completed load().

### ISSUE THREAD

**Issue by MartinBarker** [ffmpegjs/react-app#15]
hello, I am trying to use this repo on my windows 10 machine, run yarn start with no error, but when I begin to access the website and click the button to begin, I get this error in the console:
```
[info] download ffmpeg-core script (~25 MB) from https://unpkg.com/@ffmpeg/core@0.8.2/dist/ffmpeg-core.js
getCreateFFmpegCore.js:22          GET https://unpkg.com/@ffmpeg/core@0.8.2/dist/ffmpeg-core.js net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep 200
```

![image](https://user-images.githubusercontent.com/27025504/167496799-00081e7d-80da-47c9-802f-4c6abee25a61.png)

**Comment by Rits1272** [comment]
I guess downloading the `ffmpeg-core` file locally and using it on port 3000 would solve your problem

**Comment by MartinBarker** [comment]
> I guess downloading the `ffmpeg-core` file locally and using it on port 3000 would solve your problem

I was able to solve the issue by manually downloading `http` and setting it to be the <script> tag src on the page.

But now it leads to a new error:
```
[info] run FS.writeFile test.avi <289280 bytes binary file>
createFFmpeg.js:7 Uncaught (in promise) Error: ffmpeg.wasm is not ready, make sure you have completed load().
    at Object../node_modules/@ffmpeg/ffmpeg/src/createFFmpeg.js (createFFmpeg.js:7:1)
    at __webpack_require__ (bootstrap:784:1)
    at fn (bootstrap:150:1)
    at Object../node_modules/@ffmpeg/ffmpeg/src/index.js (index.js:2:1)
    at __webpack_require__ (bootstrap:784:1)
    at fn (bootstrap:150:1)
    at Module../src/App.js (App.css?4433:45:1)
    at __webpack_require__ (bootstrap:784:1)
    at fn (bootstrap:150:1)
    at Module../src/index.js (index.css?f3f6:45:1)
    at __webpack_require__ (bootstrap:784:1)
    at fn (bootstrap:150:1)
    at Object.1 (serviceWorker.js:141:1)
    at __webpack_require__ (bootstrap:784:1)
    at checkDeferredModules (bootstrap:45:1)
    at Array.webpackJsonpCallback [as push] (bootstrap:32:1)
    at main.chunk.js:1:71
```
